"""Artifact-native Memory domain and service contracts."""

from powercontext.errors import (
    CapabilityNotSupportedError,
    EmbeddingProviderUnavailableError,
    InvalidEmbeddingError,
    InvalidMemoryCandidateError,
    InvalidMemoryCitationError,
    InvalidMemoryEvidenceError,
    MemoryBackendConfigurationError,
    MemoryEntryInactiveError,
    MemoryEntryNotFoundError,
    MemoryLayerError,
)
from powercontext.memory.candidates import TaskOutcomeReport, TaskOutcomeSource, WorkingNoteCandidatePipeline
from powercontext.memory.models import (
    EmbeddingProfile,
    EmbeddingVector,
    Memory,
    MemoryCapabilities,
    MemoryChange,
    MemoryChangeOp,
    MemoryChannelHit,
    MemoryCitation,
    MemoryContent,
    MemoryEntryInput,
    MemoryEntryState,
    MemoryEntryVersion,
    MemoryHit,
    MemoryManifest,
    MemoryManifestEntry,
    MemoryMatchedBy,
    MemoryRevisionChanges,
    MemorySearchMode,
    MemorySearchResult,
    MemoryUsedSearchMode,
)
from powercontext.memory.protocols import (
    CandidatePipeline,
    EmbeddingProvider,
    MemoryBackend,
    MemoryCandidateRequest,
    MemoryCommit,
    MemoryEvidenceCodec,
    MemoryProjection,
    MemorySearchChannels,
    MemorySearchRequest,
    MemoryUnitOfWork,
)
from powercontext.memory.service import MemoryRememberMode, MemoryService

__all__ = [
    "CandidatePipeline",
    "CapabilityNotSupportedError",
    "EmbeddingProfile",
    "EmbeddingProvider",
    "EmbeddingProviderUnavailableError",
    "EmbeddingVector",
    "InvalidEmbeddingError",
    "InvalidMemoryCandidateError",
    "InvalidMemoryCitationError",
    "InvalidMemoryEvidenceError",
    "Memory",
    "MemoryBackend",
    "MemoryBackendConfigurationError",
    "MemoryCandidateRequest",
    "MemoryCapabilities",
    "MemoryChange",
    "MemoryChangeOp",
    "MemoryChannelHit",
    "MemoryCitation",
    "MemoryCommit",
    "MemoryContent",
    "MemoryEntryInactiveError",
    "MemoryEntryInput",
    "MemoryEntryNotFoundError",
    "MemoryEntryState",
    "MemoryEntryVersion",
    "MemoryEvidenceCodec",
    "MemoryHit",
    "MemoryLayerError",
    "MemoryManifest",
    "MemoryManifestEntry",
    "MemoryMatchedBy",
    "MemoryProjection",
    "MemoryRememberMode",
    "MemoryRevisionChanges",
    "MemorySearchChannels",
    "MemorySearchMode",
    "MemorySearchRequest",
    "MemorySearchResult",
    "MemoryService",
    "MemoryUnitOfWork",
    "MemoryUsedSearchMode",
    "TaskOutcomeReport",
    "TaskOutcomeSource",
    "WorkingNoteCandidatePipeline",
]
