"""Stable domain contracts for PowerContext."""

from powercontext.artifacts import Artifact, ArtifactCatalog, ArtifactDraft, ArtifactLineage, ArtifactRef, ArtifactStore
from powercontext.context import Artifacts, PowerContext, Sources
from powercontext.errors import (
    ArtifactFamilyMismatchError,
    ArtifactNotFoundError,
    PowerContextError,
    RevisionConflictError,
    SourceAdapterNotFoundError,
    SourceConflictError,
    SourceNotFoundError,
)
from powercontext.inference import (
    EmbeddingModel,
    EmbeddingResult,
    GenerationResult,
    InferenceError,
    InferenceTimeoutError,
    InferenceUnavailableError,
    InferenceUsage,
    InvalidInferenceOutputError,
    StructuredGenerator,
)
from powercontext.memory import (
    CapabilityNotSupportedError,
    EmbeddingProfile,
    Memory,
    MemoryCapabilities,
    MemoryChange,
    MemoryCitation,
    MemoryContent,
    MemoryEntryInactiveError,
    MemoryEntryInput,
    MemoryEntryNotFoundError,
    MemoryEntryVersion,
    MemoryHit,
    MemoryLayerError,
    MemoryManifest,
    MemoryManifestEntry,
    MemoryRevisionChanges,
    MemorySearchResult,
    MemoryService,
)
from powercontext.sources import Source, SourceAdapter, SourceCatalog, SourceMaterialization, SourceStore
from powercontext.triggers import Trigger

__all__ = [
    "Artifact",
    "ArtifactCatalog",
    "ArtifactDraft",
    "ArtifactFamilyMismatchError",
    "ArtifactLineage",
    "ArtifactNotFoundError",
    "ArtifactRef",
    "ArtifactStore",
    "Artifacts",
    "CapabilityNotSupportedError",
    "EmbeddingModel",
    "EmbeddingProfile",
    "EmbeddingResult",
    "GenerationResult",
    "InferenceError",
    "InferenceTimeoutError",
    "InferenceUnavailableError",
    "InferenceUsage",
    "InvalidInferenceOutputError",
    "Memory",
    "MemoryCapabilities",
    "MemoryChange",
    "MemoryCitation",
    "MemoryContent",
    "MemoryEntryInactiveError",
    "MemoryEntryInput",
    "MemoryEntryNotFoundError",
    "MemoryEntryVersion",
    "MemoryHit",
    "MemoryLayerError",
    "MemoryManifest",
    "MemoryManifestEntry",
    "MemoryRevisionChanges",
    "MemorySearchResult",
    "MemoryService",
    "PowerContext",
    "PowerContextError",
    "RevisionConflictError",
    "Source",
    "SourceAdapter",
    "SourceAdapterNotFoundError",
    "SourceCatalog",
    "SourceConflictError",
    "SourceMaterialization",
    "SourceNotFoundError",
    "SourceStore",
    "Sources",
    "StructuredGenerator",
    "Trigger",
]
