"""Shared identity limits that remain safe for utf8mb4 relational indexes."""

MAX_SCOPE_ID_LENGTH = 256
MAX_SOURCE_ID_LENGTH = 256
MAX_SOURCE_TYPE_LENGTH = 128
MAX_ARTIFACT_FAMILY_LENGTH = 128
MAX_ARTIFACT_ID_LENGTH = 128
MAX_BINDING_NAME_LENGTH = 128
MAX_EXTERNAL_SKILL_NAME_LENGTH = 128
MAX_EXTERNAL_SKILL_DESCRIPTION_LENGTH = 2_000
MAX_EXTERNAL_SKILL_HOST_ID_LENGTH = 128
MAX_EXTERNAL_SKILL_LOCATOR_LENGTH = 2_000
