"""Built-in runtime configuration, lifecycle, and application services."""

from powercontext.builtin.artifacts.memory.models import MemoryChange
from powercontext.builtin.runtime.application import (
    BuiltinRuntime,
    ContextApplication,
    MemoryApplication,
    ScheduledSourceProcessor,
    ScopedContextApplication,
    ScopedMemoryApplication,
    ScopedSourceApplication,
    SourceApplication,
)
from powercontext.builtin.runtime.composition import (
    BuiltinConfigurationError,
    open_builtin_contexts,
    open_builtin_runtime,
)
from powercontext.builtin.runtime.config import (
    BuiltinConfig,
    DatabaseConfig,
    InferenceConfig,
    RuntimeConfig,
)
from powercontext.builtin.runtime.errors import InvalidRuntimeRequestError, PreparedContextInvariantError
from powercontext.builtin.runtime.models import (
    PREPARED_CONTEXT_SCHEMA,
    CaptureSource,
    GetMemoryEntryRequest,
    MemoryChangesPage,
    MemoryCitation,
    MemoryEntriesPage,
    MemoryEntryInput,
    MemoryEntryRecord,
    MemoryEntryVersion,
    MemoryFlushResult,
    MemoryHit,
    MemoryMutationResult,
    MemoryRevisionChanges,
    MemorySearchPage,
    PrepareContextRequest,
    PreparedContext,
    PreparedContextSchema,
    PreparedContextStatus,
    RememberMemoryRequest,
    RetireMemoryEntryRequest,
    ReviseMemoryEntryRequest,
    RuntimeCapabilities,
    SearchMemoryRequest,
    SourceReceipt,
)
from powercontext.builtin.runtime.prepared_context import PreparedContextBuilder
from powercontext.builtin.runtime.protocols import PowerContextProvider

__all__ = [
    "PREPARED_CONTEXT_SCHEMA",
    "BuiltinConfig",
    "BuiltinConfigurationError",
    "BuiltinRuntime",
    "CaptureSource",
    "ContextApplication",
    "DatabaseConfig",
    "GetMemoryEntryRequest",
    "InferenceConfig",
    "InvalidRuntimeRequestError",
    "MemoryApplication",
    "MemoryChange",
    "MemoryChangesPage",
    "MemoryCitation",
    "MemoryEntriesPage",
    "MemoryEntryInput",
    "MemoryEntryRecord",
    "MemoryEntryVersion",
    "MemoryFlushResult",
    "MemoryHit",
    "MemoryMutationResult",
    "MemoryRevisionChanges",
    "MemorySearchPage",
    "PowerContextProvider",
    "PrepareContextRequest",
    "PreparedContext",
    "PreparedContextBuilder",
    "PreparedContextInvariantError",
    "PreparedContextSchema",
    "PreparedContextStatus",
    "RememberMemoryRequest",
    "RetireMemoryEntryRequest",
    "ReviseMemoryEntryRequest",
    "RuntimeCapabilities",
    "RuntimeConfig",
    "ScheduledSourceProcessor",
    "ScopedContextApplication",
    "ScopedMemoryApplication",
    "ScopedSourceApplication",
    "SearchMemoryRequest",
    "SourceApplication",
    "SourceReceipt",
    "open_builtin_contexts",
    "open_builtin_runtime",
]
