# Copyright (c) 2026 OceanBase.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Artifact-native Memory domain and service contracts."""

from powercontext.builtin.artifacts.memory.errors import (
    CapabilityNotSupportedError,
    InvalidEmbeddingError,
    InvalidMemoryCandidateError,
    InvalidMemoryCitationError,
    InvalidMemoryEvidenceError,
    MemoryBackendConfigurationError,
    MemoryEntryInactiveError,
    MemoryEntryNotFoundError,
    MemoryLayerError,
)
from powercontext.builtin.artifacts.memory.extraction import (
    DefaultMemoryEvidenceProjector,
    KnownMemoryEntryKind,
    LLMMemoryCandidatePipeline,
    MemoryEvidenceProjector,
    MemoryExtractionCandidate,
    MemoryExtractionCurrentEntry,
    MemoryExtractionEvidence,
    MemoryExtractionInput,
    MemoryExtractionIntent,
    MemoryExtractionOutput,
)
from powercontext.builtin.artifacts.memory.models import (
    EmbeddingProfile,
    Memory,
    MemoryCapabilities,
    MemoryChange,
    MemoryChangeOp,
    MemoryChannelHit,
    MemoryCitation,
    MemoryContent,
    MemoryEntryInput,
    MemoryEntryState,
    MemoryEntryVersion,
    MemoryHit,
    MemoryManifest,
    MemoryManifestEntry,
    MemoryMatchedBy,
    MemoryRerankTrace,
    MemoryRevisionChanges,
    MemorySearchMode,
    MemorySearchResult,
    MemoryUsedSearchMode,
)
from powercontext.builtin.artifacts.memory.prompts import (
    CONVERSATION_MEMORY_EXTRACTION_INSTRUCTIONS,
    CONVERSATION_MEMORY_EXTRACTION_INSTRUCTIONS_VERSION,
    MEMORY_EXTRACTION_INSTRUCTIONS,
    MEMORY_EXTRACTION_INSTRUCTIONS_VERSION,
    MemoryExtractionProfile,
    memory_extraction_instructions,
    memory_extraction_instructions_version,
)
from powercontext.builtin.artifacts.memory.protocols import (
    CandidatePipeline,
    MemoryBackend,
    MemoryCandidateRequest,
    MemoryCommit,
    MemoryProjection,
    MemorySearchChannels,
    MemorySearchRequest,
    MemoryUnitOfWork,
    MemoryWritePlan,
)
from powercontext.builtin.artifacts.memory.reranking import (
    MEMORY_RERANK_INSTRUCTIONS,
    MEMORY_RERANK_INSTRUCTIONS_VERSION,
    LLMMemoryReranker,
    MemoryRerankCandidate,
    MemoryRerankDecision,
    MemoryReranker,
    MemoryRerankInput,
    MemoryRerankMode,
    MemoryRerankOutput,
)
from powercontext.builtin.artifacts.memory.service import MemoryRememberMode, MemoryService

__all__ = [
    "CONVERSATION_MEMORY_EXTRACTION_INSTRUCTIONS",
    "CONVERSATION_MEMORY_EXTRACTION_INSTRUCTIONS_VERSION",
    "MEMORY_EXTRACTION_INSTRUCTIONS",
    "MEMORY_EXTRACTION_INSTRUCTIONS_VERSION",
    "MEMORY_RERANK_INSTRUCTIONS",
    "MEMORY_RERANK_INSTRUCTIONS_VERSION",
    "CandidatePipeline",
    "CapabilityNotSupportedError",
    "DefaultMemoryEvidenceProjector",
    "EmbeddingProfile",
    "InvalidEmbeddingError",
    "InvalidMemoryCandidateError",
    "InvalidMemoryCitationError",
    "InvalidMemoryEvidenceError",
    "KnownMemoryEntryKind",
    "LLMMemoryCandidatePipeline",
    "LLMMemoryReranker",
    "Memory",
    "MemoryBackend",
    "MemoryBackendConfigurationError",
    "MemoryCandidateRequest",
    "MemoryCapabilities",
    "MemoryChange",
    "MemoryChangeOp",
    "MemoryChannelHit",
    "MemoryCitation",
    "MemoryCommit",
    "MemoryContent",
    "MemoryEntryInactiveError",
    "MemoryEntryInput",
    "MemoryEntryNotFoundError",
    "MemoryEntryState",
    "MemoryEntryVersion",
    "MemoryEvidenceProjector",
    "MemoryExtractionCandidate",
    "MemoryExtractionCurrentEntry",
    "MemoryExtractionEvidence",
    "MemoryExtractionInput",
    "MemoryExtractionIntent",
    "MemoryExtractionOutput",
    "MemoryExtractionProfile",
    "MemoryHit",
    "MemoryLayerError",
    "MemoryManifest",
    "MemoryManifestEntry",
    "MemoryMatchedBy",
    "MemoryProjection",
    "MemoryRememberMode",
    "MemoryRerankCandidate",
    "MemoryRerankDecision",
    "MemoryRerankInput",
    "MemoryRerankMode",
    "MemoryRerankOutput",
    "MemoryRerankTrace",
    "MemoryReranker",
    "MemoryRevisionChanges",
    "MemorySearchChannels",
    "MemorySearchMode",
    "MemorySearchRequest",
    "MemorySearchResult",
    "MemoryService",
    "MemoryUnitOfWork",
    "MemoryUsedSearchMode",
    "MemoryWritePlan",
    "memory_extraction_instructions",
    "memory_extraction_instructions_version",
]
