"""Optional, read-only Handoff Report domain values."""

from powercontext.builtin.handoff_report.adapters import RuntimeHandoffReadAdapter
from powercontext.builtin.handoff_report.application import (
    HandoffReportApplication,
    ReportActivityPage,
    ReportPeriodInput,
)
from powercontext.builtin.handoff_report.canonical import (
    ReportCanonicalizationError,
    canonical_json_bytes,
    finalize_digests,
    report_digest,
    selection_digest,
    selection_envelope,
)
from powercontext.builtin.handoff_report.catalog import HandoffReportCatalog, ProjectIdFactory
from powercontext.builtin.handoff_report.catalog_store import (
    DEFAULT_CATALOG_PAGE_SIZE,
    HANDOFF_REPORT_CATALOG_TABLES,
    MAX_CATALOG_PAGE_SIZE,
    CatalogPage,
    ReportCatalogRepository,
)
from powercontext.builtin.handoff_report.errors import (
    HandoffReportBusyError,
    HandoffReportCatalogArgumentError,
    HandoffReportError,
    HandoffReportEvidenceCheckUnavailableError,
    HandoffReportInconsistentError,
    HandoffReportTooLargeError,
    InvalidStoredCatalogError,
    ProjectConflictError,
    ProjectNotFoundError,
    ScopeAlreadyGroupedError,
    WorkspaceBindingConflictError,
    WorkspaceBindingNotFoundError,
    WorkstreamConflictError,
    WorkstreamNotFoundError,
)
from powercontext.builtin.handoff_report.models import (
    ActivityAgent,
    ActivityVcsContext,
    CatalogState,
    ExternalReference,
    ExternalReferenceKind,
    GeneratedSummaryTrust,
    HandoffReportTrust,
    ProjectDescriptor,
    ReportActivityEvent,
    ReportActivitySource,
    ReportActivityTrust,
    ReportLocale,
    ReportSelectionConsistency,
    ReportSelectionEntry,
    ReportSelectionStatus,
    ReportTimeBasis,
    RepositoryProvider,
    RepositoryRef,
    WorkspaceBinding,
    WorkspaceBindingState,
    WorkstreamDescriptor,
    WorkstreamKind,
    activity_sort_key,
    normalize_repository_ref,
    normalized_sort_text,
    selection_sort_key,
    workstream_sort_key,
)
from powercontext.builtin.handoff_report.rendering import render_markdown
from powercontext.builtin.handoff_report.report import (
    HandoffReport,
    ReportActivityCoverageStatus,
    ReportActivityStatus,
    ReportCoverage,
    ReportEvidenceChecks,
    ReportFormat,
    ReportHandoffActivityRelation,
    ReportKind,
    ReportPeriodComparison,
    ReportReportingStatus,
    ReportSummary,
    ReportWorkStatus,
    WorkstreamReport,
)
from powercontext.builtin.handoff_report.selection import select_optimistic_stable_handoffs
from powercontext.builtin.handoff_report.service import HandoffReportService
from powercontext.builtin.handoff_report.workspace import WorkspaceBindingService
from powercontext.builtin.handoff_report.workspace_store import (
    HANDOFF_REPORT_WORKSPACE_BINDINGS_TABLE,
    HANDOFF_REPORT_WORKSPACE_TABLES,
    WorkspaceBindingRepository,
)

__all__ = [
    "DEFAULT_CATALOG_PAGE_SIZE",
    "HANDOFF_REPORT_CATALOG_TABLES",
    "HANDOFF_REPORT_WORKSPACE_BINDINGS_TABLE",
    "HANDOFF_REPORT_WORKSPACE_TABLES",
    "MAX_CATALOG_PAGE_SIZE",
    "ActivityAgent",
    "ActivityVcsContext",
    "CatalogPage",
    "CatalogState",
    "ExternalReference",
    "ExternalReferenceKind",
    "GeneratedSummaryTrust",
    "HandoffReport",
    "HandoffReportApplication",
    "HandoffReportBusyError",
    "HandoffReportCatalog",
    "HandoffReportCatalogArgumentError",
    "HandoffReportError",
    "HandoffReportEvidenceCheckUnavailableError",
    "HandoffReportInconsistentError",
    "HandoffReportService",
    "HandoffReportTooLargeError",
    "HandoffReportTrust",
    "InvalidStoredCatalogError",
    "ProjectConflictError",
    "ProjectDescriptor",
    "ProjectIdFactory",
    "ProjectNotFoundError",
    "ReportActivityCoverageStatus",
    "ReportActivityEvent",
    "ReportActivityPage",
    "ReportActivitySource",
    "ReportActivityStatus",
    "ReportActivityTrust",
    "ReportCanonicalizationError",
    "ReportCatalogRepository",
    "ReportCoverage",
    "ReportEvidenceChecks",
    "ReportFormat",
    "ReportHandoffActivityRelation",
    "ReportKind",
    "ReportLocale",
    "ReportPeriodComparison",
    "ReportPeriodInput",
    "ReportReportingStatus",
    "ReportSelectionConsistency",
    "ReportSelectionEntry",
    "ReportSelectionStatus",
    "ReportSummary",
    "ReportTimeBasis",
    "ReportWorkStatus",
    "RepositoryProvider",
    "RepositoryRef",
    "RuntimeHandoffReadAdapter",
    "ScopeAlreadyGroupedError",
    "WorkspaceBinding",
    "WorkspaceBindingConflictError",
    "WorkspaceBindingNotFoundError",
    "WorkspaceBindingRepository",
    "WorkspaceBindingService",
    "WorkspaceBindingState",
    "WorkstreamConflictError",
    "WorkstreamDescriptor",
    "WorkstreamKind",
    "WorkstreamNotFoundError",
    "WorkstreamReport",
    "activity_sort_key",
    "canonical_json_bytes",
    "finalize_digests",
    "normalize_repository_ref",
    "normalized_sort_text",
    "render_markdown",
    "report_digest",
    "select_optimistic_stable_handoffs",
    "selection_digest",
    "selection_envelope",
    "selection_sort_key",
    "workstream_sort_key",
]
