# generated by datamodel-codegen:
#   filename:  openapi/powercontext.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, model_validator


class ArtifactReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    artifact_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    revision: Annotated[StrictInt, Field(ge=1)]


class ApproveArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    expected_version: Annotated[StrictInt, Field(ge=1)]


class CaptureContentSourceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    content: Annotated[StrictStr, Field(max_length=200000, min_length=1)]
    metadata: dict[str, Any] | None = None


class ExperienceProposal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    situation: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]
    action: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]
    outcome: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]
    lesson: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: StrictStr
    message: StrictStr
    details: Annotated[dict[str, Any] | None, Field(...)]


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: ErrorDetail


class FlushMemoryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class GetArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]


class GetExperienceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    artifact: ArtifactReference


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: StrictStr


class ListMemoryChangesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    since_revision: Annotated[
        StrictInt | None,
        Field(
            description="Exclusive lower bound; 0 requests complete history from Revision 1. Positive nonexistent revisions are errors.",
            ge=0,
        ),
    ] = None


class ListMemoryEntriesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    include_inactive: Annotated[
        StrictBool, Field(description="Include inactive entries from the current Memory head for explicit audit.")
    ] = False


class MemoryCitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory_ref: ArtifactReference
    entry_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    entry_version_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]


class PrepareContextRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    query: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    max_bytes: Annotated[StrictInt, Field(ge=512, le=32768)] = 8000


class ReadinessStatus(StrEnum):
    READY = "ready"
    NOT_READY = "not_ready"


class RememberMemoryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    kind: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    text: Annotated[StrictStr, Field(description="Must not exceed 8192 UTF-8 bytes after normalization.", min_length=1)]
    reason: Annotated[StrictStr | None, Field(max_length=512)] = None
    expected_revision: Annotated[StrictInt | None, Field(ge=1)] = None


class RetireMemoryEntryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    citation: MemoryCitation
    reason: Annotated[StrictStr | None, Field(max_length=512)] = None


class RejectArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    expected_version: Annotated[StrictInt, Field(ge=1)]
    reason: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern=".*\\S.*")]


class ReviseMemoryEntryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    citation: MemoryCitation
    kind: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    text: Annotated[StrictStr, Field(description="Must not exceed 8192 UTF-8 bytes after normalization.", min_length=1)]
    reason: Annotated[StrictStr | None, Field(max_length=512)] = None


class SourceReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[StrictStr, Field(description="Stable Source type.")]
    source_id: StrictStr


class CaptureStatus(StrEnum):
    ACCEPTED = "accepted"


class CandidateFamily(StrEnum):
    EXPERIENCE = "experience"


class CandidateStatus(StrEnum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


class PreparedContextSchema(StrEnum):
    POWERCONTEXT_PREPARED_CONTEXT_V1 = "powercontext.prepared-context.v1"


class PreparedContextStatus(StrEnum):
    READY = "ready"
    EMPTY = "empty"


class EntryChangeOperation(StrEnum):
    ADD = "add"
    REVISE = "revise"
    DEACTIVATE = "deactivate"
    REACTIVATE = "reactivate"


class FlushStatus(StrEnum):
    IDLE = "idle"
    PROCESSED = "processed"


class MemoryEntryState(StrEnum):
    ACTIVE = "active"
    INACTIVE = "inactive"


class MemoryMatchedBy(StrEnum):
    FTS = "fts"
    VECTOR = "vector"


class MemorySearchMode(StrEnum):
    AUTO = "auto"
    FTS = "fts"
    VECTOR = "vector"
    HYBRID = "hybrid"


class MemoryUsedSearchMode(StrEnum):
    FTS = "fts"
    VECTOR = "vector"
    HYBRID = "hybrid"


class ArtifactCandidate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    version: Annotated[StrictInt, Field(ge=1)]
    family: CandidateFamily
    status: CandidateStatus
    proposal: ExperienceProposal
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: Annotated[ArtifactReference | None, Field(...)]
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)]
    result_artifact: Annotated[ArtifactReference | None, Field(...)]
    decision_reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)]

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class ArtifactCandidatePage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidates: list[ArtifactCandidate]
    next_cursor: Annotated[StrictStr | None, Field(...)]


class Capabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_types: list[StrictStr]
    artifact_families: list[StrictStr]
    memory_extraction: Annotated[StrictBool, Field(description="Whether pending Sources can be extracted into Memory.")]
    search_modes: list[MemorySearchMode]
    context_versions: list[PreparedContextSchema]


class CaptureContentSourceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: CaptureStatus
    source: SourceReference
    position: Annotated[StrictInt, Field(ge=1)]


class PreparedContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[PreparedContextSchema, Field(alias="schema")]
    status: PreparedContextStatus
    content: Annotated[StrictStr | None, Field(...)]
    content_bytes: Annotated[StrictInt, Field(ge=0)]


class EntryChange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    op: EntryChangeOperation
    entry_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    from_entry_version_id: Annotated[StrictStr | None, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    to_entry_version_id: Annotated[StrictStr | None, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    reason: Annotated[StrictStr | None, Field(...)]


class ExperienceArtifact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: ArtifactReference
    content: ExperienceProposal
    source_refs: list[SourceReference]
    artifact_refs: list[ArtifactReference]


class FlushMemoryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: FlushStatus
    previous_cursor: Annotated[StrictInt, Field(ge=0)]
    current_cursor: Annotated[StrictInt, Field(ge=0)]
    high_watermark: Annotated[StrictInt, Field(ge=0)]
    processed_source_count: Annotated[StrictInt, Field(ge=0)]
    memory: ArtifactReference | None = None


class GetMemoryEntryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    citation: MemoryCitation


class ListArtifactCandidatesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    status: CandidateStatus = CandidateStatus.PENDING
    family: CandidateFamily | None = None
    cursor: Annotated[StrictStr | None, Field(max_length=128, min_length=1)] = None
    limit: Annotated[StrictInt, Field(ge=1, le=100)] = 50


class MemoryEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    citation: MemoryCitation
    version: Annotated[StrictInt, Field(ge=1)]
    kind: StrictStr
    text: StrictStr
    state: MemoryEntryState
    source_refs: list[SourceReference]
    artifact_refs: list[ArtifactReference]


class MemoryMutationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference
    entry: MemoryEntry | None = None


class MemoryRevisionChanges(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory_ref: ArtifactReference
    changes: list[EntryChange]


class ProposeExperienceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    proposal: ExperienceProposal
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class ReadinessResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: ReadinessStatus
    checks: dict[str, StrictStr]


class ReviseArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    expected_version: Annotated[StrictInt, Field(ge=1)]
    proposal: ExperienceProposal
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class SearchMemoryHit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    citation: MemoryCitation
    text: StrictStr
    score: Annotated[StrictFloat, Field(ge=0.0, le=1.0)]
    matched_by: list[MemoryMatchedBy]


class SearchMemoryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    query: Annotated[StrictStr, Field(max_length=8192, min_length=1)]
    limit: Annotated[StrictInt, Field(ge=1, le=50)] = 10
    mode: MemorySearchMode = MemorySearchMode.AUTO


class SearchMemoryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference | None = None
    mode: MemoryUsedSearchMode | None = None
    hits: list[SearchMemoryHit]


class ListMemoryChangesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference | None = None
    revisions: list[MemoryRevisionChanges]


class ListMemoryEntriesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference | None = None
    entries: list[MemoryEntry]
